### ISSUE TITLE
How to logoff/logout or expire a JWT Token (not expire) ?

### ISSUE THREAD

**Issue by rpossan** [hayfever/sorcery-jwt#12]
I tried to log out using the sorcery method (logout) but it just updates some columns from the user but if I continue using the JWT token it will be valid until it expired by the date, not respecting the logout method.
Any idea?

**Comment by hayfever** [comment]
Token invalidation is unfortunately beyond the scope of what I set out to do here, https://waiting-for-dev.github.io/blog/2017/01/24/jwt_revocation_strategies has been my reference for when I need to invalidate tokens. 

A new version of sorcery is being worked on that should include some mechanism to handle this, you can follow the progress here: https://github.com/Sorcery/sorcery-rework/issues/9
