### ISSUE TITLE
Sorcery-jwt should support sorcery 0.16.x until sorcery 1.0 is released

### ISSUE THREAD

**Issue by kbighorse** [hayfever/sorcery-jwt#15]
in Gemfile:

```
gem 'sorcery', '~> 0.16'
```

```
bundle update sorcery
Fetching gem metadata from https://rubygems.org/.........
Resolving dependencies...
Bundler could not find compatible versions for gem "sorcery":
  In Gemfile:
    sorcery (~> 0.16)

    sorcery-jwt was resolved to 0.1.12, which depends on
      sorcery (>= 0.13, < 0.16)
```

Sorcery resolved ruby 2.7.x deprecation warnings (among other things) starting in version 0.16.0: https://github.com/Sorcery/sorcery/releases/tag/v0.16.0
https://github.com/Sorcery/sorcery/pull/241

I realize https://github.com/Sorcery/sorcery-rework will support `jwt`, but appears to be stalled. Can we catch up with core sorcery in the meantime?

Thanks so much for all your JWT work!

**Comment by hayfever** [comment]
howdy, are you on the latest version of this gem? I merged https://github.com/hayfever/sorcery-jwt/pull/14 last month which should support up to v0.17

**Comment by kbighorse** [comment]
right you are! Thanks!
